
---
- hosts: aiksdns
  tasks:
  - name: Loome allalaadimiseks kataloogi
    file:
      path=/root/allalaadimised
      owner=root
      group=root
      mode=0755
      state=directory

  - name: Allalaadime mysql_5.7 repositooriumi pakett apt-i lisamiseks
    get_url:
      url: https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb
      dest: "/root/allalaadimised"
      mode: 0440

  - name: installeerime mysql_5.7 repo
    apt: "deb=/root/allalaadimised/mysql-apt-config_0.8.22-1_all.deb"


  - name: installime mysql_5.7
    apt: name=mysql-server update_cache=yes state=present
